include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    file_names: false
    no_default_cases: false
    public_member_api_docs: false
