name: db
version: 1.0.0

environment:
  sdk: ^3.0.1

dependencies:
  json_annotation: ^4.8.1
  orm: ^3.4.3

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0
